name: calculator
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  flutter_js: ^0.8.1
  math_expressions: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/web/
    - assets/web/assets/
    - assets/web/assets/assets/
    - assets/web/assets/fonts/
    - assets/web/assets/packages/
    - assets/web/assets/packages/flutter_inappwebview/
    - assets/web/assets/packages/flutter_inappwebview/assets/
    - assets/web/assets/packages/flutter_inappwebview/assets/t_rex_runner/
    - assets/web/assets/packages/flutter_inappwebview_web/
    - assets/web/assets/packages/flutter_inappwebview_web/assets/
    - assets/web/assets/packages/flutter_inappwebview_web/assets/web/
    - assets/web/assets/packages/flutter_js/
    - assets/web/assets/packages/flutter_js/assets/
    - assets/web/assets/packages/flutter_js/assets/js/
    - assets/web/assets/shaders/
    - assets/web/canvaskit/
    - assets/web/canvaskit/chromium/
    - assets/web/icons/
#    - assets/canvaskit/
#    - assets/icons/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
